# Generated by Django 2.0 on 2022-03-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220304_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagepost',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
